version: '3.7'

services:
  nginx:
    build:
      context: .
      target: grocy-nginx
      args:
        GROCY_VERSION: ${GROCY_VERSION}
    depends_on:
    - php
    environment:
      PHP_HOST: php
    ports:
    - '8080:8080'

  php:
    build:
      context: .
      target: grocy-php
      args:
        GROCY_VERSION: ${GROCY_VERSION}
    environment:
      PHP_MEMORY_LIMIT:    512M
      MAX_UPLOAD:          50M
      PHP_MAX_FILE_UPLOAD: 200
      PHP_MAX_POST:        100M
      GROCY_CULTURE:       en
