apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grocy.fullnamePhp" . }}
  labels:
    {{- include "grocy.labelsPhp" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCountPhp }}
  selector:
    matchLabels:
      {{- include "grocy.selectorLabelsPhp" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grocy.selectorLabelsPhp" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "grocy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/php:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: php-fpm
            containerPort: 9000
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: php-fpm
          readinessProbe:
            tcpSocket:
              port: php-fpm
          envFrom:
          - configMapRef:
              name: {{ include "grocy.fullnamePhp" . }}
          volumeMounts:
          - mountPath: /www/data
            name: data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
      - name: data
        image: busybox
        command: ["sh", "-c", "touch -a /www/data/config.php && mkdir -p /www/data/viewcache"]
        volumeMounts:
        - name: data
          mountPath: /www/data
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "grocy.fullnamePhp" .) }}
        {{- else }}
        emptyDir: {}
        {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
