apiVersion: v1
kind: Service
metadata:
  name: {{ include "grocy.fullname" . }}-php
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
    app.kubernetes.io/component: php
spec:
  ports:
    - port: 9000
      targetPort: php-fpm
      protocol: TCP
      name: php-fpm
  selector:
    {{- include "grocy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: php
