apiVersion: v1
kind: Service
metadata:
  name: {{ include "grocy.fullnamePhp" . }}
  labels:
    {{- include "grocy.labelsPhp" . | nindent 4 }}
spec:
  ports:
    - port: 9000
      targetPort: php-fpm
      protocol: TCP
      name: php-fpm
  selector:
    {{- include "grocy.selectorLabelsPhp" . | nindent 4 }}
