apiVersion: v1
kind: Service
metadata:
  name: {{ include "grocy.fullname" . }}-nginx
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "grocy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
