apiVersion: v1
kind: Service
metadata:
  name: {{ include "grocy.fullnameNginx" . }}
  labels:
    {{- include "grocy.labelsNginx" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "grocy.selectorLabelsNginx" . | nindent 4 }}
